using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MiniGame_Battleships_Net5
{
    class Board
    {
        #region Board Grids
        public static Grid[,] CreateRadar(GridManager gridManager)
        {
            Grid[,] radarGrid = new Grid[10, 10];
            {
                { radarGrid[0, 0] = gridManager.CreatePosition("A0", false, false); radarGrid[0, 1] = gridManager.CreatePosition("A1", false, false); radarGrid[0, 2] = gridManager.CreatePosition("A2", false, false); radarGrid[0, 3] = gridManager.CreatePosition("A3", false, false); radarGrid[0, 4] = gridManager.CreatePosition("A4", false, false); radarGrid[0, 5] = gridManager.CreatePosition("A5", false, false); radarGrid[0, 6] = gridManager.CreatePosition("A6", false, false); radarGrid[0, 7] = gridManager.CreatePosition("A7", false, false); radarGrid[0, 8] = gridManager.CreatePosition("A8", false, false); radarGrid[0, 9] = gridManager.CreatePosition("A9", false, false); }
                { radarGrid[1, 0] = gridManager.CreatePosition("B0", false, false); radarGrid[1, 1] = gridManager.CreatePosition("B1", false, false); radarGrid[1, 2] = gridManager.CreatePosition("B2", false, false); radarGrid[1, 3] = gridManager.CreatePosition("B3", false, false); radarGrid[1, 4] = gridManager.CreatePosition("B4", false, false); radarGrid[1, 5] = gridManager.CreatePosition("B5", false, false); radarGrid[1, 6] = gridManager.CreatePosition("B6", false, false); radarGrid[1, 7] = gridManager.CreatePosition("B7", false, false); radarGrid[1, 8] = gridManager.CreatePosition("B8", false, false); radarGrid[1, 9] = gridManager.CreatePosition("B9", false, false); }
                { radarGrid[2, 0] = gridManager.CreatePosition("C0", false, false); radarGrid[2, 1] = gridManager.CreatePosition("C1", false, false); radarGrid[2, 2] = gridManager.CreatePosition("C2", false, false); radarGrid[2, 3] = gridManager.CreatePosition("C3", false, false); radarGrid[2, 4] = gridManager.CreatePosition("C4", false, false); radarGrid[2, 5] = gridManager.CreatePosition("C5", false, false); radarGrid[2, 6] = gridManager.CreatePosition("C6", false, false); radarGrid[2, 7] = gridManager.CreatePosition("C7", false, false); radarGrid[2, 8] = gridManager.CreatePosition("C8", false, false); radarGrid[2, 9] = gridManager.CreatePosition("C9", false, false); }
                { radarGrid[3, 0] = gridManager.CreatePosition("D0", false, false); radarGrid[3, 1] = gridManager.CreatePosition("D1", false, false); radarGrid[3, 2] = gridManager.CreatePosition("D2", false, false); radarGrid[3, 3] = gridManager.CreatePosition("D3", false, false); radarGrid[3, 4] = gridManager.CreatePosition("D4", false, false); radarGrid[3, 5] = gridManager.CreatePosition("D5", false, false); radarGrid[3, 6] = gridManager.CreatePosition("D6", false, false); radarGrid[3, 7] = gridManager.CreatePosition("D7", false, false); radarGrid[3, 8] = gridManager.CreatePosition("D8", false, false); radarGrid[3, 9] = gridManager.CreatePosition("D9", false, false); }
                { radarGrid[4, 0] = gridManager.CreatePosition("E0", false, false); radarGrid[4, 1] = gridManager.CreatePosition("E1", false, false); radarGrid[4, 2] = gridManager.CreatePosition("E2", false, false); radarGrid[4, 3] = gridManager.CreatePosition("E3", false, false); radarGrid[4, 4] = gridManager.CreatePosition("E4", false, false); radarGrid[4, 5] = gridManager.CreatePosition("E5", false, false); radarGrid[4, 6] = gridManager.CreatePosition("E6", false, false); radarGrid[4, 7] = gridManager.CreatePosition("E7", false, false); radarGrid[4, 8] = gridManager.CreatePosition("E8", false, false); radarGrid[4, 9] = gridManager.CreatePosition("E9", false, false); }
                { radarGrid[5, 0] = gridManager.CreatePosition("F0", false, false); radarGrid[5, 1] = gridManager.CreatePosition("F1", false, false); radarGrid[5, 2] = gridManager.CreatePosition("F2", false, false); radarGrid[5, 3] = gridManager.CreatePosition("F3", false, false); radarGrid[5, 4] = gridManager.CreatePosition("F4", false, false); radarGrid[5, 5] = gridManager.CreatePosition("F5", false, false); radarGrid[5, 6] = gridManager.CreatePosition("F6", false, false); radarGrid[5, 7] = gridManager.CreatePosition("F7", false, false); radarGrid[5, 8] = gridManager.CreatePosition("F8", false, false); radarGrid[5, 9] = gridManager.CreatePosition("F9", false, false); }
                { radarGrid[6, 0] = gridManager.CreatePosition("G0", false, false); radarGrid[6, 1] = gridManager.CreatePosition("G1", false, false); radarGrid[6, 2] = gridManager.CreatePosition("G2", false, false); radarGrid[6, 3] = gridManager.CreatePosition("G3", false, false); radarGrid[6, 4] = gridManager.CreatePosition("G4", false, false); radarGrid[6, 5] = gridManager.CreatePosition("G5", false, false); radarGrid[6, 6] = gridManager.CreatePosition("G6", false, false); radarGrid[6, 7] = gridManager.CreatePosition("G7", false, false); radarGrid[6, 8] = gridManager.CreatePosition("G8", false, false); radarGrid[6, 9] = gridManager.CreatePosition("G9", false, false); }
                { radarGrid[7, 0] = gridManager.CreatePosition("H0", false, false); radarGrid[7, 1] = gridManager.CreatePosition("H1", false, false); radarGrid[7, 2] = gridManager.CreatePosition("H2", false, false); radarGrid[7, 3] = gridManager.CreatePosition("H3", false, false); radarGrid[7, 4] = gridManager.CreatePosition("H4", false, false); radarGrid[7, 5] = gridManager.CreatePosition("H5", false, false); radarGrid[7, 6] = gridManager.CreatePosition("H6", false, false); radarGrid[7, 7] = gridManager.CreatePosition("H7", false, false); radarGrid[7, 8] = gridManager.CreatePosition("H8", false, false); radarGrid[7, 9] = gridManager.CreatePosition("H9", false, false); }
                { radarGrid[8, 0] = gridManager.CreatePosition("I0", false, false); radarGrid[8, 1] = gridManager.CreatePosition("I1", false, false); radarGrid[8, 2] = gridManager.CreatePosition("I2", false, false); radarGrid[8, 3] = gridManager.CreatePosition("I3", false, false); radarGrid[8, 4] = gridManager.CreatePosition("I4", false, false); radarGrid[8, 5] = gridManager.CreatePosition("I5", false, false); radarGrid[8, 6] = gridManager.CreatePosition("I6", false, false); radarGrid[8, 7] = gridManager.CreatePosition("I7", false, false); radarGrid[8, 8] = gridManager.CreatePosition("I8", false, false); radarGrid[8, 9] = gridManager.CreatePosition("I9", false, false); }
                { radarGrid[9, 0] = gridManager.CreatePosition("J0", false, false); radarGrid[9, 1] = gridManager.CreatePosition("J1", false, false); radarGrid[9, 2] = gridManager.CreatePosition("J2", false, false); radarGrid[9, 3] = gridManager.CreatePosition("J3", false, false); radarGrid[9, 4] = gridManager.CreatePosition("J4", false, false); radarGrid[9, 5] = gridManager.CreatePosition("J5", false, false); radarGrid[9, 6] = gridManager.CreatePosition("J6", false, false); radarGrid[9, 7] = gridManager.CreatePosition("J7", false, false); radarGrid[9, 8] = gridManager.CreatePosition("J8", false, false); radarGrid[9, 9] = gridManager.CreatePosition("J9", false, false); }
            };
            return radarGrid;
        }

        public static Grid[,] CreateTerritory(GridManager gridManager)
        {
            Grid[,] territoryGrid = new Grid[10, 10];
            {
                { territoryGrid[0, 0] = gridManager.CreatePosition("A0", false, false); territoryGrid[0, 1] = gridManager.CreatePosition("A1", false, false); territoryGrid[0, 2] = gridManager.CreatePosition("A2", false, false); territoryGrid[0, 3] = gridManager.CreatePosition("A3", false, false); territoryGrid[0, 4] = gridManager.CreatePosition("A4", false, false); territoryGrid[0, 5] = gridManager.CreatePosition("A5", false, false); territoryGrid[0, 6] = gridManager.CreatePosition("A6", false, false); territoryGrid[0, 7] = gridManager.CreatePosition("A7", false, false); territoryGrid[0, 8] = gridManager.CreatePosition("A8", false, false); territoryGrid[0, 9] = gridManager.CreatePosition("A9", false, false); }
                { territoryGrid[1, 0] = gridManager.CreatePosition("B0", false, false); territoryGrid[1, 1] = gridManager.CreatePosition("B1", false, false); territoryGrid[1, 2] = gridManager.CreatePosition("B2", false, false); territoryGrid[1, 3] = gridManager.CreatePosition("B3", false, false); territoryGrid[1, 4] = gridManager.CreatePosition("B4", false, false); territoryGrid[1, 5] = gridManager.CreatePosition("B5", false, false); territoryGrid[1, 6] = gridManager.CreatePosition("B6", false, false); territoryGrid[1, 7] = gridManager.CreatePosition("B7", false, false); territoryGrid[1, 8] = gridManager.CreatePosition("B8", false, false); territoryGrid[1, 9] = gridManager.CreatePosition("B9", false, false); }
                { territoryGrid[2, 0] = gridManager.CreatePosition("C0", false, false); territoryGrid[2, 1] = gridManager.CreatePosition("C1", false, false); territoryGrid[2, 2] = gridManager.CreatePosition("C2", false, false); territoryGrid[2, 3] = gridManager.CreatePosition("C3", false, false); territoryGrid[2, 4] = gridManager.CreatePosition("C4", false, false); territoryGrid[2, 5] = gridManager.CreatePosition("C5", false, false); territoryGrid[2, 6] = gridManager.CreatePosition("C6", false, false); territoryGrid[2, 7] = gridManager.CreatePosition("C7", false, false); territoryGrid[2, 8] = gridManager.CreatePosition("C8", false, false); territoryGrid[2, 9] = gridManager.CreatePosition("C9", false, false); }
                { territoryGrid[3, 0] = gridManager.CreatePosition("D0", false, false); territoryGrid[3, 1] = gridManager.CreatePosition("D1", false, false); territoryGrid[3, 2] = gridManager.CreatePosition("D2", false, false); territoryGrid[3, 3] = gridManager.CreatePosition("D3", false, false); territoryGrid[3, 4] = gridManager.CreatePosition("D4", false, false); territoryGrid[3, 5] = gridManager.CreatePosition("D5", false, false); territoryGrid[3, 6] = gridManager.CreatePosition("D6", false, false); territoryGrid[3, 7] = gridManager.CreatePosition("D7", false, false); territoryGrid[3, 8] = gridManager.CreatePosition("D8", false, false); territoryGrid[3, 9] = gridManager.CreatePosition("D9", false, false); }
                { territoryGrid[4, 0] = gridManager.CreatePosition("E0", false, false); territoryGrid[4, 1] = gridManager.CreatePosition("E1", false, false); territoryGrid[4, 2] = gridManager.CreatePosition("E2", false, false); territoryGrid[4, 3] = gridManager.CreatePosition("E3", false, false); territoryGrid[4, 4] = gridManager.CreatePosition("E4", false, false); territoryGrid[4, 5] = gridManager.CreatePosition("E5", false, false); territoryGrid[4, 6] = gridManager.CreatePosition("E6", false, false); territoryGrid[4, 7] = gridManager.CreatePosition("E7", false, false); territoryGrid[4, 8] = gridManager.CreatePosition("E8", false, false); territoryGrid[4, 9] = gridManager.CreatePosition("E9", false, false); }
                { territoryGrid[5, 0] = gridManager.CreatePosition("F0", false, false); territoryGrid[5, 1] = gridManager.CreatePosition("F1", false, false); territoryGrid[5, 2] = gridManager.CreatePosition("F2", false, false); territoryGrid[5, 3] = gridManager.CreatePosition("F3", false, false); territoryGrid[5, 4] = gridManager.CreatePosition("F4", false, false); territoryGrid[5, 5] = gridManager.CreatePosition("F5", false, false); territoryGrid[5, 6] = gridManager.CreatePosition("F6", false, false); territoryGrid[5, 7] = gridManager.CreatePosition("F7", false, false); territoryGrid[5, 8] = gridManager.CreatePosition("F8", false, false); territoryGrid[5, 9] = gridManager.CreatePosition("F9", false, false); }
                { territoryGrid[6, 0] = gridManager.CreatePosition("G0", false, false); territoryGrid[6, 1] = gridManager.CreatePosition("G1", false, false); territoryGrid[6, 2] = gridManager.CreatePosition("G2", false, false); territoryGrid[6, 3] = gridManager.CreatePosition("G3", false, false); territoryGrid[6, 4] = gridManager.CreatePosition("G4", false, false); territoryGrid[6, 5] = gridManager.CreatePosition("G5", false, false); territoryGrid[6, 6] = gridManager.CreatePosition("G6", false, false); territoryGrid[6, 7] = gridManager.CreatePosition("G7", false, false); territoryGrid[6, 8] = gridManager.CreatePosition("G8", false, false); territoryGrid[6, 9] = gridManager.CreatePosition("G9", false, false); }
                { territoryGrid[7, 0] = gridManager.CreatePosition("H0", false, false); territoryGrid[7, 1] = gridManager.CreatePosition("H1", false, false); territoryGrid[7, 2] = gridManager.CreatePosition("H2", false, false); territoryGrid[7, 3] = gridManager.CreatePosition("H3", false, false); territoryGrid[7, 4] = gridManager.CreatePosition("H4", false, false); territoryGrid[7, 5] = gridManager.CreatePosition("H5", false, false); territoryGrid[7, 6] = gridManager.CreatePosition("H6", false, false); territoryGrid[7, 7] = gridManager.CreatePosition("H7", false, false); territoryGrid[7, 8] = gridManager.CreatePosition("H8", false, false); territoryGrid[7, 9] = gridManager.CreatePosition("H9", false, false); }
                { territoryGrid[8, 0] = gridManager.CreatePosition("I0", false, false); territoryGrid[8, 1] = gridManager.CreatePosition("I1", false, false); territoryGrid[8, 2] = gridManager.CreatePosition("I2", false, false); territoryGrid[8, 3] = gridManager.CreatePosition("I3", false, false); territoryGrid[8, 4] = gridManager.CreatePosition("I4", false, false); territoryGrid[8, 5] = gridManager.CreatePosition("I5", false, false); territoryGrid[8, 6] = gridManager.CreatePosition("I6", false, false); territoryGrid[8, 7] = gridManager.CreatePosition("I7", false, false); territoryGrid[8, 8] = gridManager.CreatePosition("I8", false, false); territoryGrid[8, 9] = gridManager.CreatePosition("I9", false, false); }
                { territoryGrid[9, 0] = gridManager.CreatePosition("J0", false, false); territoryGrid[9, 1] = gridManager.CreatePosition("J1", false, false); territoryGrid[9, 2] = gridManager.CreatePosition("J2", false, false); territoryGrid[9, 3] = gridManager.CreatePosition("J3", false, false); territoryGrid[9, 4] = gridManager.CreatePosition("J4", false, false); territoryGrid[9, 5] = gridManager.CreatePosition("J5", false, false); territoryGrid[9, 6] = gridManager.CreatePosition("J6", false, false); territoryGrid[9, 7] = gridManager.CreatePosition("J7", false, false); territoryGrid[9, 8] = gridManager.CreatePosition("J8", false, false); territoryGrid[9, 9] = gridManager.CreatePosition("J9", false, false); }
            };
            return territoryGrid;
        }

        public static Grid[,] CreateEnemyTerritory(GridManager gridManager)
        {
            Grid[,] enemyGrid = new Grid[10, 10];
            {
                { enemyGrid[0, 0] = gridManager.CreatePosition("A0", false, false); enemyGrid[0, 1] = gridManager.CreatePosition("A1", false, false); enemyGrid[0, 2] = gridManager.CreatePosition("A2", false, false); enemyGrid[0, 3] = gridManager.CreatePosition("A3", false, false); enemyGrid[0, 4] = gridManager.CreatePosition("A4", false, false); enemyGrid[0, 5] = gridManager.CreatePosition("A5", false, false); enemyGrid[0, 6] = gridManager.CreatePosition("A6", false, false); enemyGrid[0, 7] = gridManager.CreatePosition("A7", false, false); enemyGrid[0, 8] = gridManager.CreatePosition("A8", false, false); enemyGrid[0, 9] = gridManager.CreatePosition("A9", false, false); }
                { enemyGrid[1, 0] = gridManager.CreatePosition("B0", false, false); enemyGrid[1, 1] = gridManager.CreatePosition("B1", false, false); enemyGrid[1, 2] = gridManager.CreatePosition("B2", false, false); enemyGrid[1, 3] = gridManager.CreatePosition("B3", false, false); enemyGrid[1, 4] = gridManager.CreatePosition("B4", false, false); enemyGrid[1, 5] = gridManager.CreatePosition("B5", false, false); enemyGrid[1, 6] = gridManager.CreatePosition("B6", false, false); enemyGrid[1, 7] = gridManager.CreatePosition("B7", false, false); enemyGrid[1, 8] = gridManager.CreatePosition("B8", false, false); enemyGrid[1, 9] = gridManager.CreatePosition("B9", false, false); }
                { enemyGrid[2, 0] = gridManager.CreatePosition("C0", false, false); enemyGrid[2, 1] = gridManager.CreatePosition("C1", false, false); enemyGrid[2, 2] = gridManager.CreatePosition("C2", false, false); enemyGrid[2, 3] = gridManager.CreatePosition("C3", false, false); enemyGrid[2, 4] = gridManager.CreatePosition("C4", false, false); enemyGrid[2, 5] = gridManager.CreatePosition("C5", false, false); enemyGrid[2, 6] = gridManager.CreatePosition("C6", false, false); enemyGrid[2, 7] = gridManager.CreatePosition("C7", false, false); enemyGrid[2, 8] = gridManager.CreatePosition("C8", false, false); enemyGrid[2, 9] = gridManager.CreatePosition("C9", false, false); }
                { enemyGrid[3, 0] = gridManager.CreatePosition("D0", false, false); enemyGrid[3, 1] = gridManager.CreatePosition("D1", false, false); enemyGrid[3, 2] = gridManager.CreatePosition("D2", false, false); enemyGrid[3, 3] = gridManager.CreatePosition("D3", false, false); enemyGrid[3, 4] = gridManager.CreatePosition("D4", false, false); enemyGrid[3, 5] = gridManager.CreatePosition("D5", false, false); enemyGrid[3, 6] = gridManager.CreatePosition("D6", false, false); enemyGrid[3, 7] = gridManager.CreatePosition("D7", false, false); enemyGrid[3, 8] = gridManager.CreatePosition("D8", false, false); enemyGrid[3, 9] = gridManager.CreatePosition("D9", false, false); }
                { enemyGrid[4, 0] = gridManager.CreatePosition("E0", false, false); enemyGrid[4, 1] = gridManager.CreatePosition("E1", false, false); enemyGrid[4, 2] = gridManager.CreatePosition("E2", false, false); enemyGrid[4, 3] = gridManager.CreatePosition("E3", false, false); enemyGrid[4, 4] = gridManager.CreatePosition("E4", false, false); enemyGrid[4, 5] = gridManager.CreatePosition("E5", false, false); enemyGrid[4, 6] = gridManager.CreatePosition("E6", false, false); enemyGrid[4, 7] = gridManager.CreatePosition("E7", false, false); enemyGrid[4, 8] = gridManager.CreatePosition("E8", false, false); enemyGrid[4, 9] = gridManager.CreatePosition("E9", false, false); }
                { enemyGrid[5, 0] = gridManager.CreatePosition("F0", false, false); enemyGrid[5, 1] = gridManager.CreatePosition("F1", false, false); enemyGrid[5, 2] = gridManager.CreatePosition("F2", false, false); enemyGrid[5, 3] = gridManager.CreatePosition("F3", false, false); enemyGrid[5, 4] = gridManager.CreatePosition("F4", false, false); enemyGrid[5, 5] = gridManager.CreatePosition("F5", false, false); enemyGrid[5, 6] = gridManager.CreatePosition("F6", false, false); enemyGrid[5, 7] = gridManager.CreatePosition("F7", false, false); enemyGrid[5, 8] = gridManager.CreatePosition("F8", false, false); enemyGrid[5, 9] = gridManager.CreatePosition("F9", false, false); }
                { enemyGrid[6, 0] = gridManager.CreatePosition("G0", false, false); enemyGrid[6, 1] = gridManager.CreatePosition("G1", false, false); enemyGrid[6, 2] = gridManager.CreatePosition("G2", false, false); enemyGrid[6, 3] = gridManager.CreatePosition("G3", false, false); enemyGrid[6, 4] = gridManager.CreatePosition("G4", false, false); enemyGrid[6, 5] = gridManager.CreatePosition("G5", false, false); enemyGrid[6, 6] = gridManager.CreatePosition("G6", false, false); enemyGrid[6, 7] = gridManager.CreatePosition("G7", false, false); enemyGrid[6, 8] = gridManager.CreatePosition("G8", false, false); enemyGrid[6, 9] = gridManager.CreatePosition("G9", false, false); }
                { enemyGrid[7, 0] = gridManager.CreatePosition("H0", false, false); enemyGrid[7, 1] = gridManager.CreatePosition("H1", false, false); enemyGrid[7, 2] = gridManager.CreatePosition("H2", false, false); enemyGrid[7, 3] = gridManager.CreatePosition("H3", false, false); enemyGrid[7, 4] = gridManager.CreatePosition("H4", false, false); enemyGrid[7, 5] = gridManager.CreatePosition("H5", false, false); enemyGrid[7, 6] = gridManager.CreatePosition("H6", false, false); enemyGrid[7, 7] = gridManager.CreatePosition("H7", false, false); enemyGrid[7, 8] = gridManager.CreatePosition("H8", false, false); enemyGrid[7, 9] = gridManager.CreatePosition("H9", false, false); }
                { enemyGrid[8, 0] = gridManager.CreatePosition("I0", false, false); enemyGrid[8, 1] = gridManager.CreatePosition("I1", false, false); enemyGrid[8, 2] = gridManager.CreatePosition("I2", false, false); enemyGrid[8, 3] = gridManager.CreatePosition("I3", false, false); enemyGrid[8, 4] = gridManager.CreatePosition("I4", false, false); enemyGrid[8, 5] = gridManager.CreatePosition("I5", false, false); enemyGrid[8, 6] = gridManager.CreatePosition("I6", false, false); enemyGrid[8, 7] = gridManager.CreatePosition("I7", false, false); enemyGrid[8, 8] = gridManager.CreatePosition("I8", false, false); enemyGrid[8, 9] = gridManager.CreatePosition("I9", false, false); }
                { enemyGrid[9, 0] = gridManager.CreatePosition("J0", false, false); enemyGrid[9, 1] = gridManager.CreatePosition("J1", false, false); enemyGrid[9, 2] = gridManager.CreatePosition("J2", false, false); enemyGrid[9, 3] = gridManager.CreatePosition("J3", false, false); enemyGrid[9, 4] = gridManager.CreatePosition("J4", false, false); enemyGrid[9, 5] = gridManager.CreatePosition("J5", false, false); enemyGrid[9, 6] = gridManager.CreatePosition("J6", false, false); enemyGrid[9, 7] = gridManager.CreatePosition("J7", false, false); enemyGrid[9, 8] = gridManager.CreatePosition("J8", false, false); enemyGrid[9, 9] = gridManager.CreatePosition("J9", false, false); }
            };
            return enemyGrid;
        }
        #endregion

        #region Ship Types
        public static Ship CreateHangarShip(ShipManager shipManager)
        {
            Ship hangarShip = shipManager.CreateShip("Hangar Ship", "HS", 5, 5);

            return hangarShip;
        }

        public static Ship CreateBattleship(ShipManager shipManager)
        {
            Ship battleship = shipManager.CreateShip("Battleship", "BS", 4, 4);

            return battleship;
        }
        public static Ship CreateDestroyer(ShipManager shipManager)
        {
            Ship destroyer = shipManager.CreateShip("Destroyer", "DS", 3, 3);

            return destroyer;
        }
        public static Ship CreateSubmarine(ShipManager shipManager)
        {
            Ship Submarine = shipManager.CreateShip("Submarine", "SM", 3, 3);

            return Submarine;
        }
        public static Ship CreatePatrolBoat(ShipManager shipManager)
        {
            Ship patrolBoat = shipManager.CreateShip("Patrol Boat", "PB", 2, 2);

            return patrolBoat;
        }
        #endregion
    }
}
